### ISSUE TITLE
Items with contents are emptied on load

### ISSUE THREAD

**Issue by scarf005** [joveeater/Cataclysm-BN#10]
https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/6ae0a2fa-5ef9-4a62-ac4b-d43b21aaffdb

found out an way to reliably reproduce the [issue](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2250#pullrequestreview-1658684330) on commit 283f7b4c8c58a1033324323dfbb890209814cb84.

## steps to reproduce
1. in debug menu, spawn an ice cream.
2. put it on floor.
3. save and exit.
4. re-load the world.
5. ice cream is gone, only its container (plastic tub) is left.

<details><summary>On save items are correctly serialized.</summary>

![image](https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/02317f36-a06e-4092-878f-a1db7f2d9885)

```c++
#include "catch/catch.hpp"

#include <sstream>
#include "json.h"
#include "submap.h"
#include "game_constants.h"
#include "int_id.h"
#include "point.h"
#include "type_id.h"

namespace
{

constexpr auto json = R"([
      0,
      0,
      [
        {
          "typeid": "plastic_bucket",
          "bday": 633682,
          "owner": "your_followers",
          "last_rot_check": 0,
          "drop_token": {
            "turn": 633682,
            "drop_number": 2,
            "parent_number": 2
          },
          "contents": {
            "items": [
              {
                "typeid": "icecream",
                "charges": 34,
                "bday": 633682,
                "active": true,
                "last_rot_check": 633682,
                "item_tags": ["COLD"]
              }
            ]
          }
        }
      ]
    ])";
} // namespace

TEST_CASE( "submap deserialize item with contents", "[submap][item][item_contents][serde]" )
{
    std::istringstream iss( json );
    JsonIn jsin( iss );
    submap sm( tripoint_zero );
    sm.load( jsin, "items", 28, tripoint_zero );

    const auto &items = sm.get_items( point_zero );
    REQUIRE( items.size() == 1 );

    const auto& bucket = items.front();
    CHECK( bucket->typeId() == itype_id( "plastic_bucket" ) );
    CHECK( !bucket->contents.empty() );

    const auto &contents = bucket->contents.all_items_top();
    CHECK( contents.size() == 1 );

    const auto &icecream = contents.front();
    REQUIRE( icecream->typeId() == itype_id( "icecream" ) );
}
```

submaps will also correctly load items. not sure what's causing this.

</details> 

_Originally posted by @scarf005 in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2250#pullrequestreview-1663160854_

**Comment by joveeater** [comment]
Fixed by [02fab74](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2250/commits/02fab74601c27dd8ad5206ad763f608fc1836f70)
