### ISSUE TITLE
Error on disassembling

### ISSUE THREAD

**Issue by scarf005** [joveeater/Cataclysm-BN#9]
based on latest commit 283f7b4c8c58a1033324323dfbb890209814cb84.

https://github.com/cataclysmbnteam/Cataclysm-BN/assets/54838975/c7de3381-1ded-4e4f-ad51-3d20cfbbc81d

disassembling`(B)` a plastic tub with pocket knife will result in following error:
1. `Attempting to erase something from a vector with more than 1 active iterator`
2. `Attempting to push_back to a vector with active iterators`

doing it again will result in following error:
1. `Tried to find where of an item without a location`
2. `position called on [plastic tubs] without a position`
3. `Tried to detach [plastic tubs] not in a location.`
4. `Attempting to push_back to a vector with active iterators`

and despite the message 'you salvaged 27 plastic chunks`, it is nowhere to be seen.

[debug.log](https://github.com/cataclysmbnteam/Cataclysm-BN/files/12840003/debug.log)

_Originally posted by @scarf005 in https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2250#pullrequestreview-1663174921_

**Comment by joveeater** [comment]
fixed by [6ca5680](https://github.com/cataclysmbnteam/Cataclysm-BN/pull/2250/commits/6ca5680ebe2eacdbb9bca438a2a101d3fcd3ce9b)
